export const RANDOM_CALLING  = 'RANDOM/RANDOM_CALLING';
export const RANDOM_RECEIVE  = 'RANDOM/RANDOM_RECEIVE';
export const RANDOM_SUCCESS  = 'RANDOM/RANDOM_SUCCESS';
export const RANDOM_ERROR    = 'RANDOM/RANDOM_ERROR';
export const RANDOM_PAGE     = 'RANDOM/RANDOM_PAGE';
export const RANDOM_RELEASE  = 'RANDOM/RANDOM_RELEASE';
export const RANDOM_TOTAL    = 'RANDOM/RANDOM_TOTAL';
export const RANDOM_PREVIOUS = 'RANDOM/RANDOM_PREVIOUS';
