export default {
  prevContainer: {
    backgroundColor: 'rgba(255, 255, 255, 0.70)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'flex-end',
    justifyContent: 'center',
    height: 367,
    width: 185,
  },
  placeholderPrev: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 150,
    height: 150,
    backgroundColor: '#EAFDFA',
  },
  prevImage: {
    width: 60,
    height: 65,
  },
  prevTitle: {
    color: '#8BE3CF',
    fontSize: 18,
    textAlign: 'center',
    fontFamily: 'Roboto-Thin',
    padding: 0,
    margin: 0,
  },
  prevAlbum: {
    color: '#37D9B4',
    fontSize: 22,
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
    marginRight: 10,
    marginTop: 20,
    marginBottom: 10,
  },
  prevArtists: {
    color: '#37D9B4',
    fontSize: 20,
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    marginRight: 10,
    marginTop: 10,
    marginBottom: 20,
  },
  noPrevAlbum: {
    color: '#8BE3CF',
    fontSize: 20,
    fontFamily: 'Roboto-Thin',
    width: 150,
    textAlign: 'right',
    marginRight: 10,
  },

}
