export default {
  currentContainer: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: 377,
    minHeight: 500,
    height: '100%',
    backgroundColor: 'white',
    boxShadow: '0 1px 6px rgba(0, 0, 0, 0.19)',
  },
  placeholder: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'center',
    width: 310,
    height: 310,
    marginTop: 20,
    backgroundColor: '#EAFDFA',
  },
  placeholderTitle: {
    color: '#8BE3CF',
    fontSize: 24,
    fontFamily: 'Roboto-Thin',
  },
  currentAlbum: {
    color: '#37D9B4',
    fontSize: 28,
    fontFamily: 'Roboto-Bold',
    textAlign: 'center',
    paddingLeft: 33,
    paddingRight: 33,
    marginTop: 20,
    marginBottom: 10,
  },
  currentArtists: {
    color: '#37D9B4',
    fontSize: 28,
    fontFamily: 'Roboto-Regular',
    textAlign: 'center',
    paddingLeft: 33,
    paddingRight: 33,
    marginTop: 10,
    marginBottom: 20,
  },
  listenContainer: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-evenly',
    width: 310,
    marginBottom: 20,
  },
  listenText: {
    fontSize: 18,
    fontFamily: 'Roboto-Light',
    textAlign: 'center',
    color: '#37D9B4',
  },
  listenImage: {
    width: 30,
  }
}
